# permissions to do viewer fundpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fundpool-viewer-role
rules:
- apiGroups:
  - fund.example.com
  resources:
  - fundpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fund.example.com
  resources:
  - fundpools/status
  verbs:
  - get
